In [2]:
#
import pandas as pd
pd.set_option('display.max_columns', None)

# 
import numpy as np

# 
import warnings
warnings.filterwarnings('ignore')

In [29]:
df = pd.read_csv('files/hr.csv')

In [4]:
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [6]:
df.shape

(1474, 35)

In [7]:
# Se busca las columnas que tienen valores nulos
nulos = df.isnull().sum()
nulos = nulos[nulos>0]
nulos

Age                       73
BusinessTravel           117
Department                29
EducationField            58
JobSatisfaction           29
MaritalStatus            132
MonthlyIncome             14
OverTime                  44
StandardHours            164
TrainingTimesLastYear     88
YearsWithCurrManager     148
dtype: int64

In [8]:
# Porcentaje de nulos de dichas columnas
nulos_pct = round(df.isnull().sum()/df.shape[0]*100, 2)
nulos_pct = nulos_pct[nulos_pct>0]
nulos_pct

Age                       4.95
BusinessTravel            7.94
Department                1.97
EducationField            3.93
JobSatisfaction           1.97
MaritalStatus             8.96
MonthlyIncome             0.95
OverTime                  2.99
StandardHours            11.13
TrainingTimesLastYear     5.97
YearsWithCurrManager     10.04
dtype: float64

In [9]:
# Se comprueba si existen columnas duplicadas y se verifica que los numeros de empleados están repetidos
print(df.duplicated().sum())
print(df['EmployeeNumber'].duplicated().sum())

4
4

In [10]:
# Se verifica si hay negativos en las columnas
(df.select_dtypes(include='number') < 0).any().any()

np.False_

Se verifican varias cosas hasta este punto:
* Los títulos de columnas siguen la misma estética. No es necesario cambiarlos.
* JobRol tiene los textos con las mayúsculas invertidas.
* Hay 4 filas duplicadas. Confirmado en que el número de empleado se repite que debería ser un valor único.
* No hay números negativos en ninguna columna.

In [11]:
# Se comprueba que los valores de Attrition sean solo "Yes" o "No". No tiene nulos. Convertir a Booleano
df['Attrition'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [12]:
# Education es un valor numérico que mide la escala de estudios, se comprueba los valores comprendidos. No tiene nulos
df['Education'].unique()

array([2, 1, 4, 3, 5])

In [13]:
# Solo debe devolver valor "1". Se puede descartar de la lista. No aporta valor
df['EmployeeCount'].unique()

array([1])

In [14]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. No tiene nulos
df['EnvironmentSatisfaction'].unique()

array([2, 3, 4, 1])

In [15]:
# Dos valores. No tiene nulos
df['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [16]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. No tiene nulos
df['JobInvolvement'].unique()

array([3, 2, 4, 1])

In [17]:
# Jerarquía de la empresa. Valores entre 1 y 5. No tiene nulos
df['JobLevel'].unique()

array([2, 1, 3, 4, 5])

In [18]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Tiene nulos
df['JobSatisfaction'].unique()

array([ 4.,  2.,  3.,  1., nan])

In [19]:
# Cuatro valores y nulos
df['MaritalStatus'].unique()

<StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str

In [20]:
# Valores desde el 0 hasta el 9
df['NumCompaniesWorked'].unique()

array([8, 1, 6, 9, 0, 4, 5, 2, 7, 3])

In [21]:
# Se puede convertir a booleano o descartar de la lista. No aporta valor, todos los empleados son mayores de 18 años
df['Over18'].unique()

<StringArray>
['Y']
Length: 1, dtype: str

In [22]:
# Una vez cubiertos los nulos, se puede convertir a booleano
df['OverTime'].unique()

<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

In [23]:
# Valor de empresa respecto al empleado. Escala de valores entre 1 y 4, posible descarte. No conecta con la satisfacción del empleado
df['PerformanceRating'].unique()

array([3, 4])

In [24]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Sin nulos
df['RelationshipSatisfaction'].unique()

array([1, 4, 2, 3])

In [25]:
# Jornada Laboral. Todos los empleados tienen el mismo número de horas o si no el valor es nulo. Posible descarte de la lista. No aporta valor
df['StandardHours'].unique()

array([80., nan])

In [26]:
# Valores entre 0 y 3. Valor 0 indica sin acciones. Valor 1 nivel alto de acciones. Valor 2 nivel medio de acciones. Valor 3 nivel bajo de acciones
df['StockOptionLevel'].unique()

array([0, 1, 3, 2])

In [27]:
# Valor de formaciones que se ha recibido en el último año. Escala de valores entre 0 y 6. Con nulos. Convertir a INT al retirar nulos
df['TrainingTimesLastYear'].unique()

array([ 0.,  3.,  2.,  5.,  1.,  4., nan,  6.])

In [28]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Sin nulos
df['WorkLifeBalance'].unique()

array([1, 3, 2, 4])

Se identifican las siguientes cuestiones:

* Las columnas `Attrition`, `Over18` y `OverTime` son valores booleanos en STR. No siguen el mismo formato.
* Las columnas `EmployeeCount`, `Over18`, `PerformanceRating` y `StandardHours` no aportan valor claro al estudio. Es necesario determinar si se descartan valores o se quieren conservar.
* Hay columnas en float que deben pasar a INT una vez corregidos los nulos.
* Se comprueba que las columnas con encuestas de satisfacción siempre tienen valores del 1 al 4.

## Limpieza y transformación de datos

In [ ]:
#Convertimos la columna Age a número entero
## Usamos Int64 en vez de int porque Age tiene valores nulos.
# El tipo Int64 permite trabajar con enteros y mantener los nulos como <NA>.
df['Age'] = df['Age'].astype('Int64')
df['Age'].dtype

Int64Dtype()

In [31]:
# Convertimos JobRole a minúsculas y eliminamos espacios sobrantes
# al principio y al final de cada valor.
df['JobRole'] = df['JobRole'].str.strip().str.lower()
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,laboratory technician,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,research scientist,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,laboratory technician,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [32]:
# 1. Comprobamos los valores únicos actuales de la columna Attrition
# Deberían aparecer únicamente los valores 'Yes' y 'No'.
df['Attrition'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [33]:
# 2. Convertimos la columna Attrition a valores booleanos
# 'Yes' se transforma en True
# 'No' se transforma en False
df['Attrition'] = df['Attrition'].map({
    'Yes': True,
    'No': False
})
df['Attrition'].unique()

array([ True, False])

In [34]:
df['Attrition'].dtype

dtype('bool')

#### Columnas interesantes para el análisis

PercentSalaryHike es el porcentaje de aumento salarial, seguramente desde la última revisión. Puede ser una variable interesante para el análisis