In [42]:
#
import pandas as pd
pd.set_option('display.max_columns', None)

# 
import numpy as np

# 
import warnings
warnings.filterwarnings('ignore')

In [43]:
df = pd.read_csv('files/hr.csv')

In [44]:
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [46]:
df.shape

(1474, 35)

In [47]:
# Se busca las columnas que tienen valores nulos
nulos = df.isnull().sum()
nulos = nulos[nulos>0]
nulos

Age                       73
BusinessTravel           117
Department                29
EducationField            58
JobSatisfaction           29
MaritalStatus            132
MonthlyIncome             14
OverTime                  44
StandardHours            164
TrainingTimesLastYear     88
YearsWithCurrManager     148
dtype: int64

In [48]:
# Porcentaje de nulos de dichas columnas
nulos_pct = round(df.isnull().sum()/df.shape[0]*100, 2)
nulos_pct = nulos_pct[nulos_pct>0]
nulos_pct

Age                       4.95
BusinessTravel            7.94
Department                1.97
EducationField            3.93
JobSatisfaction           1.97
MaritalStatus             8.96
MonthlyIncome             0.95
OverTime                  2.99
StandardHours            11.13
TrainingTimesLastYear     5.97
YearsWithCurrManager     10.04
dtype: float64

In [49]:
# Se comprueba si existen columnas duplicadas y se verifica que los numeros de empleados están repetidos
print(df.duplicated().sum())
print(df['EmployeeNumber'].duplicated().sum())

4
4

In [50]:
# Mostramos las filas con EmployeeNumber duplicado
# y las ordenamos por EmployeeNumber para ver juntas las repeticiones.
df[df['EmployeeNumber'].duplicated(keep=False)].sort_values('EmployeeNumber')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
67,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
184,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1041,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1222,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0

In [51]:
# Se verifica si hay negativos en las columnas
(df.select_dtypes(include='number') < 0).any().any()

np.False_

Se verifican varias cosas hasta este punto:
* Los títulos de columnas siguen la misma estética. No es necesario cambiarlos.
* JobRol tiene los textos con las mayúsculas invertidas.
* Hay 4 filas duplicadas. Confirmado en que el número de empleado se repite que debería ser un valor único.
* No hay números negativos en ninguna columna.

In [52]:
# Se comprueba que los valores de Attrition sean solo "Yes" o "No". No tiene nulos. Convertir a Booleano
df['Attrition'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [53]:
# Education es un valor numérico que mide la escala de estudios, se comprueba los valores comprendidos. No tiene nulos
df['Education'].unique()

array([2, 1, 4, 3, 5])

In [54]:
# Solo debe devolver valor "1". Se puede descartar de la lista. No aporta valor
df['EmployeeCount'].unique()

array([1])

In [55]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. No tiene nulos
df['EnvironmentSatisfaction'].unique()

array([2, 3, 4, 1])

In [56]:
# Dos valores. No tiene nulos
df['Gender'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [57]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. No tiene nulos
df['JobInvolvement'].unique()

array([3, 2, 4, 1])

In [58]:
# Jerarquía de la empresa. Valores entre 1 y 5. No tiene nulos
df['JobLevel'].unique()

array([2, 1, 3, 4, 5])

In [59]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Tiene nulos
df['JobSatisfaction'].unique()

array([ 4.,  2.,  3.,  1., nan])

In [60]:
# Cuatro valores y nulos
df['MaritalStatus'].unique()

<StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str

In [61]:
# Valores desde el 0 hasta el 9
df['NumCompaniesWorked'].unique()

array([8, 1, 6, 9, 0, 4, 5, 2, 7, 3])

In [62]:
# Se puede convertir a booleano o descartar de la lista. No aporta valor, todos los empleados son mayores de 18 años
df['Over18'].unique()

<StringArray>
['Y']
Length: 1, dtype: str

In [63]:
# Una vez cubiertos los nulos, se puede convertir a booleano
df['OverTime'].unique()

<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

In [64]:
# Valor de empresa respecto al empleado. Escala de valores entre 1 y 4, posible descarte. No conecta con la satisfacción del empleado
df['PerformanceRating'].unique()

array([3, 4])

In [65]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Sin nulos
df['RelationshipSatisfaction'].unique()

array([1, 4, 2, 3])

In [66]:
# Jornada Laboral. Todos los empleados tienen el mismo número de horas o si no el valor es nulo. Posible descarte de la lista. No aporta valor
df['StandardHours'].unique()

array([80., nan])

In [67]:
# Valores entre 0 y 3. Valor 0 indica sin acciones. Valor 1 nivel alto de acciones. Valor 2 nivel medio de acciones. Valor 3 nivel bajo de acciones
df['StockOptionLevel'].unique()

array([0, 1, 3, 2])

In [68]:
# Valor de formaciones que se ha recibido en el último año. Escala de valores entre 0 y 6. Con nulos. Convertir a INT al retirar nulos
df['TrainingTimesLastYear'].unique()

array([ 0.,  3.,  2.,  5.,  1.,  4., nan,  6.])

In [69]:
# Encuesta de satisfacción. Escala de valores entre 1 y 4. Sin nulos
df['WorkLifeBalance'].unique()

array([1, 3, 2, 4])

Se identifican las siguientes cuestiones:

* Las columnas `Attrition`, `Over18` y `OverTime` son valores booleanos en STR. No siguen el mismo formato.
* Las columnas `EmployeeCount`, `Over18`, `PerformanceRating` y `StandardHours` no aportan valor claro al estudio. Es necesario determinar si se descartan valores o se quieren conservar.
* Hay columnas en float que deben pasar a INT una vez corregidos los nulos.
* Se comprueba que las columnas con encuestas de satisfacción siempre tienen valores del 1 al 4.

## Limpieza y transformación de datos

In [70]:
#Convertimos la columna Age a número entero
## Usamos Int64 en vez de int porque Age tiene valores nulos.
# El tipo Int64 permite trabajar con enteros y mantener los nulos como <NA>.
df['Age'] = df['Age'].astype('Int64')
df['Age'].dtype

Int64Dtype()

In [79]:
#Convertimos la columna YearsWithCurrManager a número entero
## Usamos Int64 en vez de int porque YearsWithCurrManager tiene valores nulos.
# El tipo Int64 permite trabajar con enteros y mantener los nulos como <NA>.
df['YearsWithCurrManager'] = df['YearsWithCurrManager'].astype('Int64')
df['YearsWithCurrManager'].dtype

Int64Dtype()

In [71]:
# Convertimos JobRole a minúsculas y eliminamos espacios sobrantes
# al principio y al final de cada valor.
df['JobRole'] = df['JobRole'].str.strip().str.lower()
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sales executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,research scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,laboratory technician,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,research scientist,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,laboratory technician,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [72]:
# 1. Comprobamos los valores únicos actuales de la columna Attrition
# Deberían aparecer únicamente los valores 'Yes' y 'No'.
df['Attrition'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [73]:
# 2. Convertimos la columna Attrition a valores booleanos
# 'Yes' se transforma en True
# 'No' se transforma en False
df['Attrition'] = df['Attrition'].map({
    'Yes': True,
    'No': False
})
df['Attrition'].unique()

array([ True, False])

In [74]:
df['Attrition'].dtype

dtype('bool')

In [75]:
# Eliminamos las filas completamente duplicadas
df = df.drop_duplicates(keep='first')
print(df.duplicated().sum())

0

In [76]:
# EmployeeNumber identifica de forma única a cada empleado/a,
# por lo que lo usamos como índice del dataframe.
df = df.set_index('EmployeeNumber')

In [78]:
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,41,True,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,94,3,2,sales executive,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
2,49,False,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,3,Male,61,2,2,research scientist,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
4,37,True,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,Male,92,2,1,laboratory technician,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
5,33,False,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,4,Female,56,3,1,research scientist,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
7,27,False,Travel_Rarely,591,Research & Development,2,1,Medical,1,1,Male,40,3,1,laboratory technician,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0
8,32,False,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,4,Male,79,3,1,laboratory technician,4.0,Single,3068.0,11864,0,Y,No,13,3,3,80.0,0,8,2.0,2,7,7,3,6.0
10,59,False,Travel_Rarely,1324,Research & Development,3,3,Medical,1,3,Female,81,4,1,laboratory technician,1.0,Married,2670.0,9964,4,Y,NaN,20,4,1,NaN,3,12,3.0,2,1,0,0,NaN
11,30,False,Travel_Rarely,1358,NaN,24,1,Life Sciences,1,4,Male,67,3,1,laboratory technician,3.0,Divorced,2693.0,13335,1,Y,No,22,4,2,80.0,1,1,2.0,3,1,0,0,0.0
12,38,False,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,4,Male,44,2,3,manufacturing director,3.0,Single,9526.0,8787,0,Y,No,21,4,2,80.0,0,10,2.0,3,9,7,1,8.0
13,36,False,Travel_Rarely,1299,Research & Development,27,3,NaN,1,3,Male,94,3,2,healthcare representative,3.0,Married,5237.0,16577,6,Y,No,13,3,2,80.0,2,17,3.0,2,7,7,7,NaN

## Avances hasta este punto:
- Transformación de 'Age' y 'YearsWithCurrManager' a números enteros con formato int64 para que siga reconociendo los nulos y luego hacer la gestión de nulos
- Normalización de los valores en la columna JobRole
- Transformación a booleano de columna Attrition (que no tenía nulos)
- Tras comprobar que las filas repetidas eran exactamente iguales, se han eliminado las duplicadas quedándonos con la primera, y después EmployeeNumber se ha fijado como index de la tabla

#### Columnas interesantes para el análisis

PercentSalaryHike es el porcentaje de aumento salarial, seguramente desde la última revisión. Puede ser una variable interesante para el análisis